name: nest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pytorch==2.5.1
  - torchvision==0.20.1
  - trimesh==4.11.1=pyh7b2049a_0
  - matplotlib-base==3.6
prefix: /home/dj2615/Documents/work/miniconda3/envs/nest
